// <auto-generated />
using System;
using ConferenciasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConferenciasAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703225413_InitialCreate4")]
    partial class InitialCreate4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConferenciasAPI.Models.Asistente", b =>
                {
                    b.Property<int>("asistente_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("asistente_id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("conferencia_id")
                        .HasColumnType("int");

                    b.Property<int?>("conferencia_id1")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("asistente_id");

                    b.HasIndex("conferencia_id1");

                    b.ToTable("Asistentes");
                });

            modelBuilder.Entity("ConferenciasAPI.Models.Conferencia", b =>
                {
                    b.Property<int>("conferencia_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("conferencia_id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ubicacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("conferencia_id");

                    b.ToTable("Conferencias");
                });

            modelBuilder.Entity("ConferenciasAPI.Models.Asistente", b =>
                {
                    b.HasOne("ConferenciasAPI.Models.Conferencia", "Conferencia")
                        .WithMany()
                        .HasForeignKey("conferencia_id1");

                    b.Navigation("Conferencia");
                });
#pragma warning restore 612, 618
        }
    }
}
